export const CREATE_LIST = "CREATE_LIST";
export const CREATE_LIST_ERROR = "CREATE_LIST_ERROR";
export const CREATE_LIST_LOADING = "CREATE_LIST_LOADING";
export const DELETE_ITEM_LIST = "DELETE_ITEM_LIST";
export const CREATE_ITEM_LIST = "CREATE_NEW_ITEM";
export const SELECT_ACTUAL_ITEM = "SELECT_ACTUAL_ITEM";
export const CLEAN_ACTUAL_ITEM = "CLEAN_ACTUAL_ITEM";
export const EDIT_ITEM_LIST = "EDIT_ITEM_LIST";
export const CHANGE_ITEM_STATUS = "CHANGE_ITEM_STATUS";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGOUT = "USER_LOGOUT";
